### ISSUE TITLE
double class .knopf in README

### ISSUE THREAD

**Issue by mechanoid** [team-video/knopf.css#2]
hey, 

is there a practical reason for the `.knopf.knopf` construct in the README?
I find that very confusing, and it might lead people to think about specificity as a reason or such, 
but AFAIK this does not increase specificity at all. 

Thx!

**Comment by mechanoid** [comment]
I really am confused by this again. But got me, it is specificity! Thanks!

**Comment by HiroAgustin** [comment]
Hey @mechanoid, sorry I missed your comment.

We do purposely increase the specificity, the reasoning being: if you have an `active` class on your stylesheet, we don’t its styles to override ours (or cause some unexpected behaviour). If you want to override/extend the library’s active styles, it should be as simple as doing `.knopf.active { YOUR_STYLES }`.

Hope this answer helps instead of making it even more confusing
